spring:
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobilele?allowPublicRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: 'root'
    password: 'swear'
jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: create-drop
sql:
    init:
      platform: mysql