spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobilele?allowPublicRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}

#data.sql -> importing data to database if dropped
  sql:
    init:
      mode: never

#delete and patch requests enabled
mvc:
  hiddenmethod:
    filter:
      enable: true

openexchangerates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${APP_ID:}
  symbols: EUR, BGN, USD
  enable: false




   # For Checking how is Hibernate working -> Fetch types and @NamedEntityGraph
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE




#sql:
#    init:
#      platform: mysql
